CREATE TABLE `FATO_EXPORTACAO` (
  `CO_ANO` SMALLINT,
  `CO_MES` TINYINT,
  `CO_SH4` INT,
  `CO_PAIS` INT,
  `SG_MUN` VARCHAR(2),
  `CO_MUN` INT,
  `CO_DATA` DATE,
  `KG_LIQUIDO` FLOAT NOT NULL,
  `VL_FOB_US` FLOAT NOT NULL,
  `VL_FOB_BR` FLOAT NOT NULL
);

CREATE TABLE `DIM_TEMPO` (
  `CO_DATA` DATE PRIMARY KEY NOT NULL,
  `DATA_REFERENCIA` DATE,
  `ANO` SMALLINT,
  `MES` TINYINT,
  `NOME_MES` VARCHAR(10),
  `TRIMESTRE` TINYINT,
  `SEMESTRE` TINYINT
);

CREATE TABLE `DIM_PRODUTO` (
  `CO_SH4` INT PRIMARY KEY NOT NULL,
  `NO_SH4_POR` VARCHAR(255) NOT NULL
);

CREATE TABLE `DIM_PAIS` (
  `CO_PAIS` INT PRIMARY KEY NOT NULL,
  `CO_PAIS_ISOA3` VARCHAR(3),
  `CO_PAIS_ISON3` VARCHAR(3),
  `NO_PAIS` VARCHAR(100)
);

CREATE TABLE `DIM_UF_MUN` (
  `CO_MUN` INT PRIMARY KEY NOT NULL,
  `NO_MUN_MIN` VARCHAR(100),
  `SG_UF` VARCHAR(2)
);

ALTER TABLE `FATO_EXPORTACAO` ADD FOREIGN KEY (`CO_DATA`) REFERENCES `DIM_TEMPO` (`CO_DATA`);

ALTER TABLE `FATO_EXPORTACAO` ADD FOREIGN KEY (`CO_SH4`) REFERENCES `DIM_PRODUTO` (`CO_SH4`);

ALTER TABLE `FATO_EXPORTACAO` ADD FOREIGN KEY (`CO_PAIS`) REFERENCES `DIM_PAIS` (`CO_PAIS`);

ALTER TABLE `FATO_EXPORTACAO` ADD FOREIGN KEY (`CO_MUN`) REFERENCES `DIM_UF_MUN` (`CO_MUN`);
